name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: sudo apt update

      - run: |
         cd src/
         gcc -w main.c node.c parse.tab.c squ_run.c vm_stack.c vm_exec.c value.c squ_math.c
